Add Elastic Api Version header
logstash-plugins/logstash-input-elasticsearch pull request #195
Opened 2023-09-04 15:21 UTC by kaisecheng

This commit adds "Elastic-Api-Version" : "2023-10-31" to request header when the Elasticsearch is serverless

2023-09-13 21:56 UTC, jsvd requested changes
inspecting the request done by the manticore adapter in the ES ruby client, we can see the header is not being sent to the server.
a simple test is to bump the date to 2024 and confirm that we can still query a serverless deployment.
My suspicion is around header handling between the headers passed during client creation vs headers passed at request time.

2023-09-13 22:41 UTC, kaisecheng commented
Good catch! The client got headers but completely ignored and [overwritten](https://github.com/elastic/elastic-transport-ruby/blob/main/lib/elastic/transport/transport/http/manticore.rb#L93C31-L93C47) by initial headers. It seems a bug only in manticore implementation as [faraday](https://github.com/elastic/elastic-transport-ruby/blob/main/lib/elastic/transport/transport/http/faraday.rb#L39C43-L39C43) and [curb](https://github.com/elastic/elastic-transport-ruby/blob/main/lib/elastic/transport/transport/http/curb.rb#L37C39-L37C39) do a merge with the input headers.

2023-09-14 14:28 UTC, kaisecheng commented
link the upstream issue https://github.com/elastic/elastic-transport-ruby/issues/66

2023-09-25 13:23 UTC, kaisecheng commented
upstream has merged the fix. We are now waiting for the release of new version

2023-09-28 16:28 UTC, jsvd approved these changes
minor code style fixes. Tested and works great. Would love to not have to have this add_headers constantly, but requires deeper refactoring.
LGTM

2023-09-28 16:28 UTC, jsvd commented on lib/logstash/inputs/elasticsearch.rb
> +  end
in these cases we can get rid of the level of indentation and just do:

```suggestion
  def test_serverless_connection!
    @client.info(:headers => DEFAULT_EAV_HEADER ) if serverless?
  rescue => e
    @logger.error("Failed to retrieve Elasticsearch info", message: e.message, exception: e.class, backtrace: e.backtrace)
    raise LogStash::ConfigurationError, "Could not connect to a compatible version of Elasticsearch"
  end
```

2023-09-28 16:28 UTC, jsvd commented on lib/logstash/inputs/elasticsearch.rb
> +  def build_flavor
```suggestion
  end

  def build_flavor
```

2023-09-29 00:46 UTC, kaisecheng commented
@jsvd The last commit recreated the client with header. es-input should be straightforward to replace the client

2023-09-29 13:31 UTC, jsvd approved these changes
LGTM

2023-09-29 13:43 UTC, kaisecheng commented
link the issue for cleaning up resources https://github.com/logstash-plugins/logstash-input-elasticsearch/issues/196

2023-09-29 14:11 UTC, merged